spring:
  application:
    name: producer-${PRODUCER_ID:producer-ERROR}
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

server:
  port: ${PORT:10000}
  tomcat:
    max-swallow-size: 209715200
    max-http-form-post-size: 209715200

eureka:
  client:
    service-url:
      defaultZone: ${PEER_1_URL:http://localhost:8761/eureka}
#    register-with-eureka: true
#    fetch-registry: true
logging:
  logstash:
    destinationOne: ${LOGSTASH_DESTINATION_ONE:localhost:5000}
    destinationTwo: ${LOGSTASH_DESTINATION_TWO:localhost:5001}
    destinationThree: ${LOGSTASH_DESTINATION_THREE:localhost:5002}

#name of products file
products:
  file:
    name: "products.json"
  count: 1000

management:
  endpoints:
    web:
      exposure:
        include: "*"