spring:
  application:
    name: producer-${PRODUCER_ID:producer-ERROR}

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: ${PEER_1_URL:http://eurekaserver.com/eureka}
#    register-with-eureka: true
#    fetch-registry: true
logging:
  logstash:
    destination: ${LOGSTASH_DESTINATION:localhost:5000}

#name of products file

products:
  file:
    name: "products.json"
  count: 1000