spring:
  application:
    name: producer-${PRODUCER_ID:producer-ERROR}

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: ${PEER_1_URL:http://eurekaserver.com/eureka}
#    register-with-eureka: true
#    fetch-registry: true
logging:
  logstash:
    destinationOne: ${LOGSTASH_DESTINATION_ONE:localhost:5000}
    destinationTwo: ${LOGSTASH_DESTINATION_TWO:localhost:5001}
    destinationThree: ${LOGSTASH_DESTINATION_THREE:localhost:5002}

#name of products file
products:
  file:
    name: "products.json"
  count: 1000

management:
  endpoints:
    web:
      exposure:
        include: "*"